# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 700fd3af674fa90284d4ebb04d99760b7fead3bd6feb96fbb60671d19d0c2ef9125e840160ddf96cd22b5b2776207861965444b3aa404e8cda3ce81ae5e4a867

test:
  secret_key_base: 5b5c1a94db0968ebd812f50128fe7cb52c4ca5ee8d22ab84d8ece25af964119c8853e69752f1154aef32e161924c02ddba23db6ac6f7265e1ca1e9ae2a43b70d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
